# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "scrabble_trie",
    srcs = ["scrabble_trie.cc"],
    deps = ["//src/lib:ThisLib"],
)
cc_binary(
    name = "speed_test",
    srcs = ["speed_test.cc"],
    deps = ["//src/lib:ThisLib"],
)
